# Generated by Django 4.2.4 on 2023-08-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_by_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followed_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
