# Generated by Django 4.2.4 on 2023-08-29 15:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_followed_by_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='../static/img/placeholder_avatar.png', null=True, upload_to=users.models.upload_to_profile),
        ),
    ]
