# Generated by Django 4.2.4 on 2023-08-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0002_alter_comment_like_count_alter_comment_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='instaapp.tag'),
        ),
    ]
